### ISSUE TITLE
Decoding schema error

### ISSUE THREAD

**Issue by shlatchz** [loganjspears/slackchess#10]
`schema: invalid path "trigger_id"`

	&{
		abc123
		T5XUD7V40
		shlatchz
		def456 
		random
		U5YJKNTJ6
		shlatchz
		/chess
		play @slackbot
		https://hooks.slack.com/commands/T5XUD7V40/229590183571/XjOHn6zg3hYOsnSxEBcsGSOe
	}
	 
	 
	 map[
		channel_id:[def456]
		user_name:[shlatchz]
		trigger_id:[229590183683.201965267136.875204e14f8e9fc744c7d8760a68e3cd]
		user_id:[U5YJKNTJ6]
		team_id:[T5XUD7V40]
		channel_name:[random]
		team_domain:[shlatchz]
		response_url:[https://hooks.slack.com/commands/T5XUD7V40/229590183571/XjOHn6zg3hYOsnSxEBcsGSOe]
		command:[/chess]
		text:[play @slackbot]
		token:[abc123]
	]

**Comment by shlatchz** [comment]
Added `trigger_id` to `SlashCmd` schema:

	type SlashCmd struct {
		Token       string `schema:"token"`
		TeamID      string `schema:"team_id"`
		TeamDomain  string `schema:"team_domain"`
		ChannelID   string `schema:"channel_id"`
		ChannelName string `schema:"channel_name"`
		UserID      string `schema:"user_id"`
		UserName    string `schema:"user_name"`
		Command     string `schema:"command"`
		Text        string `schema:"text"`
		ResponseURL string `schema:"response_url"`
		TriggerID	string `schema:"trigger_id"`
	}

in `slackchess\internal\slack\slash.go`

**Comment by etekweb** [comment]
This issue wasn't actually added to the repo.
A pull request should be made to fix this for other users.
